CREATE TABLE ORDERWORKEJB (
    WORKID INTEGER NOT NULL,
    ORDERID INTEGER NOT NULL,
    TWOPHASE SMALLINT NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    ATTEMPTCOUNT INTEGER NOT NULL,
    MAXATTEMPTS INTEGER NOT NULL,
    AVAILABLEAT TIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP NOT NULL,
    LASTERROR VARCHAR(512),
    CONSTRAINT ORDERWORKEJB_PK PRIMARY KEY (WORKID),
    CONSTRAINT ORDERWORKEJB_ORDER_UQ UNIQUE (ORDERID)
);

CREATE INDEX ORDERWORKEJB_STATUS_IDX ON ORDERWORKEJB (STATUS, AVAILABLEAT);

INSERT INTO KEYGENEJB (KEYNAME, KEYVAL) VALUES ('orderwork', 0);